income=input("Enter your monthly income: ")
income=float(income)
expenses=input("Enter your total monthly expenses: ")
expenses=float(expenses)
monthly_savings=(income-expenses)
print=("Your monthly savings are ",monthly_savings)
projected_savings=(monthly_savings*12*0.05)
print=("Your projected savings after one year,with interest,is:",projected_savings)